### PR TITLE
Export job status counts

### PR DESCRIPTION
**Pull request by pedropombeiro**
This PR adds support for exposing the counters for jobs exposed by `/api/jobs`. This way we can keep track of the progress of long-running jobs.

### CODE REVIEW

**Review by martabal — APPROVED** [review]
Nice !
Thank you for this PR.

**Comment by pedropombeiro** [comment]
You're welcome, thanks for merging it!

Here is the intermediate result (I'll probably open another MR with this later on, and maybe some more metrics):

image

**Comment by martabal** [comment]
Looks great.
Thank you for your work

**Comment by pedropombeiro** [comment]
@martabal just to make sure, you didn't publish a Docker image, right?

**Comment by martabal** [comment]
Yes, not yet

**Pull request merged**
